builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s
  - -w
  - -X github.com/stern/stern/cmd.version={{.Version}}
  - -X github.com/stern/stern/cmd.commit={{.Commit}}
  - -X github.com/stern/stern/cmd.date={{.Date}}
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
archives:
- builds:
  - stern
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  files:
  - LICENSE
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
