version: 2
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s
  - -w
  - -X github.com/hogklint/tailfin/cmd/tailfincmd.version={{.Version}}
  - -X github.com/hogklint/tailfin/cmd/tailfincmd.commit={{.Commit}}
  - -X github.com/hogklint/tailfin/cmd/tailfincmd.date={{.Date}}
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  main: ./cmd/tailfin
archives:
- builds:
  - tailfin
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz
  files:
  - LICENSE
  wrap_in_directory: false
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
